name: Update Harvest Timesheet

on:
  workflow_dispatch:  # allows manual trigger
  schedule:
    - cron: '0 4 * * 5'  # Runs at 4 PM NZT (UTC+12), which is 4 AM UTC every Friday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make install

      - name: Run the script
        env:
          PAGERDUTY_API_TOKEN: ${{ secrets.PAGERDUTY_API_TOKEN }}
          PAGERDUTY_USER_ID: ${{ secrets.PAGERDUTY_USER_ID }}
          HARVEST_ACCOUNT_ID: ${{ secrets.HARVEST_ACCOUNT_ID }}
          HARVEST_ACCESS_TOKEN: ${{ secrets.HARVEST_ACCESS_TOKEN }}
          CALENDAR_ID: ${{ secrets.CALENDAR_ID }}
          SERVICE_ACCOUNT_JSON_B64: ${{ secrets.SERVICE_ACCOUNT_JSON_B64 }}
        run: python -m harvest_auto_timesheet
